name: Baloot

on:
  push: []

jobs:
  build_baloot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache-dependency-path: |
             ingestion_api/go.sum
      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -failfast -v -coverprofile=coverage.out ./...

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code coverage report
          path: ingestion_api/coverage.out
